deploy:
  needs: [test]
  runs-on: ubuntu-latest

  steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/server
          npm -v
          rm -r build
          git pull origin main
          npm install
          npm run build
          pm2 restart nestServer
